services:
  postgres:
    ports:
      - "127.0.0.1:5432:5432"

  minio:
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"

  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/nabiljarrai/batal-backend:latest}
    pull_policy: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    ports:
      - "127.0.0.1:8080:8080"

  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/nabiljarrai/batal-frontend:latest}
    pull_policy: always
    environment:
      NEXT_PUBLIC_API_URL: https://${DOMAIN:-batal.nabiljarrai.com}/api
    ports:
      - "127.0.0.1:3000:3000"
